### ISSUE TITLE
New release breaks existing docker build using GFDL_atmos_cubed_sphere main

### ISSUE THREAD

**Issue by StevePny** [NOAA-GFDL/SHiELD_physics#7]
System:
Ubuntu docker container using arm64/m1.

The new release (April 1, 2022) breaks my current build:

44 7.251 /fv3_gfsphysics/GFS_layer/GFS_typedefs.F90:8:12:
#44 7.251 
#44 7.251     8 |        use gfdl_cld_mp_mod,          only: rhow
#44 7.251       |            1
#44 7.251 Fatal Error: Cannot open module file 'gfdl_cld_mp_mod.mod' for reading at (1): No such file or directory
#44 7.251 compilation terminated.
#44 7.253 make: *** [Makefile_gfs:31: GFS_typedefs.o] Error 1
#44 7.254 make: *** Waiting for unfinished jobs....

The old branch 'old_main' still builds with no problem.

Where is gfdl_cld_mp_mod?

In GFS_driver, it seems like main is replacing:
```
use gfdl_cloud_microphys_mod, only: gfdl_cloud_microphys_init
#ifndef fvGFS_2017
  use cloud_diagnosis_mod,      only: cloud_diagnosis_init
```
with:
```
use gfdl_cld_mp_mod,          only: gfdl_cld_mp_init
#ifndef fvGFS_2017
  use cld_eff_rad_mod,          only: cld_eff_rad_init
#endif
```

However, in https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/blob/main/driver/SHiELD/gfdl_cloud_microphys.F90
this still has the old name:
```
module gfdl_cloud_microphys_mod
...
! =======================================================================
! initialization of gfdl cloud microphysics
! =======================================================================

!subroutine gfdl_cloud_microphys_init (id, jd, kd, axes, time)
subroutine gfdl_cloud_microphys_init (me, master, nlunit, input_nml_file, logunit, fn_nml)
```

**Comment by laurenchilutti** [comment]
Hi Steve,  We will be making a release to GFDL_atmos_cubed_sphere and a build system to accompany this release.  In the meantime please continue to use old_main.  I will update you here on this issue when the GFDL_atmos_cubed_sphere and SHiELD_build are released.

**Comment by laurenchilutti** [comment]
Hi Steve,

Please see our latest releases:
[GFDL_atmos_cubed_Sphere - 202204](https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/releases/tag/FV3-202204-public)
[SHiELD_build - 202204](https://github.com/NOAA-GFDL/SHiELD_build/releases/tag/FV3-202204-public)

These should work just fine to build SHiELD with this SHiELD_physics main branch (which is the FV3-202204-public release)

If you have any issues please feel free to open a new issue!
