### ISSUE TITLE
Requested aerosol data file "INPUT/aerosol.dat" not found!

### ISSUE THREAD

**Issue by StevePny** [NOAA-GFDL/SHiELD_physics#9]
I am running with the new 202204 version, and I now get this runtime error:
```
Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG
     Requested aerosol data file "INPUT/aerosol.dat               " not found!
     *** Stopped in subroutine aero_init !!
Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG
     Requested aerosol data file "INPUT/aerosol.dat               " not found!
     *** Stopped in subroutine aero_init !!
     Requested aerosol data file "INPUT/aerosol.dat               " not found!
Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG
     *** Stopped in subroutine aero_init !!
     Requested aerosol data file "INPUT/aerosol.dat               " not found!
     *** Stopped in subroutine aero_init !!
Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG
```
Where can I get the "aerosol.dat" file, or instructions for creating it?

**Comment by lharris4** [comment]
Hi, Steve. The aerosol.dat, among other files, are part of the set of
static input files for SHiELD (similar to those for the MRW application).
This should be available within the SHiELD container.

Thanks,
Lucas

**Comment by StevePny** [comment]
Hi @lharris4,

Thanks, I'm not sure how I lost the file, it looks like it was there before but wasn't needed/used by the previous pre-202204 release so I must have deleted it from my test case.

The link on this site to the fixed files in the docker callout window appears to be inactive/missing:
https://www.gfdl.noaa.gov/shield/shield-in-a-box/

I found an aerosol.dat file in the regional_Laura.zip experiment case files provided for the Singularity case:
https://zenodo.org/record/5090124/files/regional_Laura.zip

And also in the global_nest_Laura experiment case down at the bottom of the page:
https://zenodo.org/record/5090124/files/global_nest_Laura.zip

**Comment by lharris4** [comment]
Hi, Steve. This link:

https://zenodo.org/record/5090124/files/GFS_fix.zip

still works for me and has a 146 GB file.

The aerosol.dat file has been part of SHiELD that we originally got from
the original GSM, so it should always need it to run.

Thanks for going through all of this closely, which is very useful for
establishing our public release capabilities.

Lucas
